# Generated by Django 5.1.5 on 2025-02-03 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuários',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('email', models.EmailField(max_length=128)),
                ('senha', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
